version: '3'

services:
  app:
    build: .
    image: pokerserver:latest
    stdin_open: true
    tty: true
    volumes:
      - "$PWD:/app"
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file: env_variables.env

  db:
    image: postgres:10
    ports:
      - 5432:5432
    env_file: env_variables.env
